/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
package com.ygxc.aqjy.entity.user;

import java.sql.Timestamp;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import com.ygxc.aqjy.common.structure.IBusinessEntity;

/**
 * 权限表(t_auth)
 * 
 *
 * 
 */
@TableName("t_auth")
public class AuthEntity implements java.io.Serializable, IBusinessEntity {
    /** 版本号 */
    private static final long serialVersionUID = -3818117130038635848L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ID */
    @TableId(value = "id",type = IdType.INPUT)
    private String id;

    /** 名称 */
    private String name;

    /** 权限编号 */
    private String code;

    /** URL */
    private String url;

    /** 父ID */
    private String parentId;
    
    /** 排序，只影响平级 */
    private Integer sort;

    /** 创建时间 */
    private Timestamp createTime;

    /** 修改时间 */
    private Timestamp updateTime;

    /** 是否删除，0：否；1：是 */
    @TableLogic(value = "0")
    private Integer isDelete;

    /** 操作人ID */
    private String opUserId;

    /** 操作人 */
    private String opUserName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取ID
     * 
     * @return ID
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置ID
     * 
     * @param id
     *          ID
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取名称
     * 
     * @return 名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置名称
     * 
     * @param name
     *          名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取权限编号
     * 
     * @return 权限编号
     */
    public String getCode() {
        return this.code;
    }

    /**
     * 设置权限编号
     * 
     * @param code
     *          权限编号
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 获取URL
     * 
     * @return URL
     */
    public String getUrl() {
        return this.url;
    }

    /**
     * 设置URL
     * 
     * @param url
     *          URL
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 获取父ID
     * 
     * @return 父ID
     */
    public String getParentId() {
        return this.parentId;
    }

    /**
     * 设置父ID
     * 
     * @param parentId
     *          父ID
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取修改时间
     * 
     * @return 修改时间
     */
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置修改时间
     * 
     * @param updateTime
     *          修改时间
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取是否删除，0：否；1：是
     * 
     * @return 是否删除
     */
    public Integer getIsDelete() {
        return this.isDelete;
    }

    /**
     * 设置是否删除，0：否；1：是
     * 
     * @param isDelete
     *          是否删除
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * 获取操作人ID
     * 
     * @return 操作人ID
     */
    public String getOpUserId() {
        return this.opUserId;
    }

    /**
     * 设置操作人ID
     * 
     * @param opUserId
     *          操作人ID
     */
    public void setOpUserId(String opUserId) {
        this.opUserId = opUserId;
    }

    /**
     * 获取操作人
     * 
     * @return 操作人
     */
    public String getOpUserName() {
        return this.opUserName;
    }

    /**
     * 设置操作人
     * 
     * @param opUserName
     *          操作人
     */
    public void setOpUserName(String opUserName) {
        this.opUserName = opUserName;
    }
    
    public void setSort(Integer sort) {
		this.sort = sort;
	}
    
    public Integer getSort() {
		return sort;
	}

    /* This code was generated by TableGo tools, mark 2 end. */
}
