/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
package com.ygxc.aqjy.entity.user;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * 角色权限关系表(t_role_auth)
 * 
 * @author 
 * @version 
 */
@TableName("t_role_auth")
public class RoleAuthEntity implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -3440429411708297102L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** 角色ID */
    @TableId(value = "id",type = IdType.INPUT)
    private String roleId;

    /** 权限ID */
    private String authId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取角色ID
     * 
     * @return 角色ID
     */
    public String getRoleId() {
        return this.roleId;
    }

    /**
     * 设置角色ID
     * 
     * @param roleId
     *          角色ID
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * 获取权限ID
     * 
     * @return 权限ID
     */
    public String getAuthId() {
        return this.authId;
    }

    /**
     * 设置权限ID
     * 
     * @param authId
     *          权限ID
     */
    public void setAuthId(String authId) {
        this.authId = authId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}
