/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
package com.ygxc.aqjy.entity.user;

import java.sql.Timestamp;
import com.baomidou.mybatisplus.annotation.TableLogic;
import com.baomidou.mybatisplus.annotation.TableName;
import com.ygxc.aqjy.common.structure.IBusinessEntity;

/**
 * 职位角色表(t_role)
 * 
 * @author Qiaoxin.Hong
 * @version 1.0.0 2020-03-26
 */
@TableName("t_role")
public class RoleEntity implements java.io.Serializable, IBusinessEntity {
    /** 版本号 */
    private static final long serialVersionUID = 8638412560428694772L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** ID */
    private String id;

    /** 名称 */
    private String name;

    /** 创建时间 */
    private Timestamp createTime;

    /** 修改时间 */
    private Timestamp updateTime;

    /** 是否删除，0：否；1：是 */
    @TableLogic
    private Integer isDelete;

    /** 操作人ID */
    private String opUserId;

    /** 操作人 */
    private String opUserName;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取ID
     * 
     * @return ID
     */
    public String getId() {
        return this.id;
    }

    /**
     * 设置ID
     * 
     * @param id
     *          ID
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * 获取名称
     * 
     * @return 名称
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置名称
     * 
     * @param name
     *          名称
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取创建时间
     * 
     * @return 创建时间
     */
    public Timestamp getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置创建时间
     * 
     * @param createTime
     *          创建时间
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * 获取修改时间
     * 
     * @return 修改时间
     */
    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    /**
     * 设置修改时间
     * 
     * @param updateTime
     *          修改时间
     */
    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * 获取是否删除，0：否；1：是
     * 
     * @return 是否删除
     */
    public Integer getIsDelete() {
        return this.isDelete;
    }

    /**
     * 设置是否删除，0：否；1：是
     * 
     * @param isDelete
     *          是否删除
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * 获取操作人ID
     * 
     * @return 操作人ID
     */
    public String getOpUserId() {
        return this.opUserId;
    }

    /**
     * 设置操作人ID
     * 
     * @param opUserId
     *          操作人ID
     */
    public void setOpUserId(String opUserId) {
        this.opUserId = opUserId;
    }

    /**
     * 获取操作人
     * 
     * @return 操作人
     */
    public String getOpUserName() {
        return this.opUserName;
    }

    /**
     * 设置操作人
     * 
     * @param opUserName
     *          操作人
     */
    public void setOpUserName(String opUserName) {
        this.opUserName = opUserName;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}
