server:
  port: 5130
  
#swagger配置信息
swagger:
  basePackage: com.ygxc.aqjy.controller
  title: AQJY RESTful API
  version: 1.0


mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ygxc.aqjy.entity
  # 枚举类 扫描路径
  type-enums-package: com.ygxc.aqjy.common.constant
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 0
      logic-not-delete-value: 1
    #刷新mapper 调试神器
    refresh: true
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志打印
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    #默认枚举处理类,如果配置了该属性,枚举将统一使用指定处理器进行处理.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:23306/aqjy?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    
#Redis数据库索引（默认为0）
redis:
  database: 0
#Redis服务器地址
  hostName: 192.168.1.6:6379
#Redis服务器连接密码（默认为空）
  password :
#连接池最大连接数（使用负值表示没有限制）
  jedis:
    pool:
      max-active: 20
#连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
#连接池中的最大空闲连接
      max-idle: 10
#连接池中的最小空闲连接
      min-idle: 0
#连接超时时间（毫秒）
  timeout: 1000
  
#操作日志开关
oplogSwitch: true

